services:
  # Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  # Cache & Messaging
  redis:
    image: redis:7-alpine
    restart: always

  # Backend (API + WebSockets)
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start.sh
    volumes:
      - static_volume:/app/static # Share static files with Nginx
    expose:
      - "8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_URL=/django_static/
    depends_on:
      - db
      - redis
    restart: always

  # Async Worker
  celery_worker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: celery -A core worker -l info
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
      - redis
    restart: always

  # Frontend + Reverse Proxy
  nginx:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80" # The only public port
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static # Read what Django generated
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
